### ISSUE TITLE
Nuovi programmi Impegno Civico, FDI, AVS

### ISSUE THREAD

**Issue by vi-enne** [ondata/elezioni-politiche-2022#15]
Ciao, segnalo:

Impegno Civico ha pubblicato un programma più dettagliato
https://www.impegno-civico.it/wp-content/uploads/2022/09/Programma-politico_Impegno-Civico.pdf

Fratelli d'Italia ha pubblicato un programma dettagliato sul turismo
https://www.fratelli-italia.it/wp-content/uploads/2022/08/Programma-turismo_2022.pdf

Alleanza Verdi e Sinistra ha pubblicato un programma giovani
https://verdisinistra.it/pretendiamo-il-futuro/
e un programma Italiani all'estero
https://verdisinistra.it/wp-content/uploads/2022/08/AVS_Programma-Europa.pdf

**Comment by aborruso** [comment]
grazie @vi-enne

**Comment by aborruso** [comment]
Aggiunti, grazie @vi-enne 

![image](https://user-images.githubusercontent.com/30607/189491501-82700ef9-dcd1-4e27-9560-481a367ce1ce.png)
