### ISSUE TITLE
Scaricare vincitori dei seggi

### ISSUE THREAD

**Issue by alberto-bottarini** [ondata/elezioni-politiche-2022#21]
Da ieri hanno aggiunto su eligendo anche i vincitori dei vari seggi uninominali e proporzionali.

La chiamata in questione è: https://eleapi.interno.gov.it/siel/PX/elettiSI/DE/20220925/TE/03

![Screenshot 2022-09-27 at 17 44 08](https://user-images.githubusercontent.com/1442934/192572861-02ec3395-89a3-4320-8088-14cb1acf4741.png)

**Comment by aborruso** [comment]
@alberto-bottarini  questi dati (probabilmente con qualche info in meno delle API) credo siano anche scaricabili in bulk https://elezioni.interno.gov.it/report/20220925

Mi confermi che sia come dico?

**Comment by alberto-bottarini** [comment]
Sembra di si, ma ti confermo domani dal pc. 

PS dove l'hai recuperato quel link?

**Comment by aborruso** [comment]
> PS dove l'hai recuperato quel link?

È a casa base

![image](https://user-images.githubusercontent.com/30607/192617879-6c0d2a6f-cdf8-47cd-9534-580a2b5fa627.png)

**Comment by alberto-bottarini** [comment]
Confermo, i dati sono quelli.
Grazie
Chiudo
