### ISSUE TITLE
Portale visualizzazione dati

### ISSUE THREAD

**Issue by alberto-bottarini** [ondata/elezioni-politiche-2022#26]
Ciao, sto mettendo in piedi un portale che includa tutto il set di dati raccolto e organizzato in pagine web navigabili.

L'obiettivo è quello di dare ordine a tutta la mole di dati creando pagine dedicate alle varie entità: liste, candidati, circoscrizioni... cosi da avere un flusso di navigazione comodo e coerente

Qua potete vedere la prima versione:
http://elezioni2022.albertobottarini.com

Mi piacerebbe ricevere feedback e suggerimenti/critiche.

PS l'aspetto grafico è da migliorare e mancano ancora un bel po' di dati, ma ci stiamo lavorando :)

**Comment by alberto-bottarini** [comment]
Codice sorgente disponibile qua:
https://github.com/alberto-bottarini/elezioni-2022

**Comment by aborruso** [comment]
Alberto, grazie!

Ti abbiamo aggiunto in sitografia https://github.com/ondata/elezioni-politiche-2022#sitografia-correlata
