### ISSUE TITLE
Codice comunale ISTAT - Senato

### ISSUE THREAD

**Issue by fbranda** [ondata/elezioni-politiche-2022#27]
Cari,

appena avete tempo potete aggiungere il codice comunale ISTAT anche per il file del Senato come fatto con la Camera?

**Comment by aborruso** [comment]
Ciao @fbranda ho aggiunto i Codici Istat, ai dati pubblicati ad oggi da Eligendo, per Camera e Senato
https://github.com/ondata/elezioni-politiche-2022/tree/main/affluenza-risultati/dati/Eligendo/processing
