### ISSUE TITLE
Valle d'Aosta e Trentino Alto Adige

### ISSUE THREAD

**Issue by alberto-bottarini** [ondata/elezioni-politiche-2022#29]
Ciao, analizzando i dati mi pare di capire che:

- per quanto riguarda la VdA non esistano collegi plurinominali, ma solamente uninominali sia per la Camera che per il Senato
- per quanto riguarda il TAA esistano collegi plurinominali solamente per la Camera, mentre per il senato ne esistono solo uninominali

È una assunzione corretta? È cosi per una mancanza di dati o perchè il loro status di regioni a statuto speciale fa si che ci siano queste differenze?

**Comment by aborruso** [comment]
Ciao Alberto,
con lo scraping ci siamo fermati, perché adesso ci sono dei dati qui:
https://elezioni.interno.gov.it/report/20220925

Da [qui](https://www.rainews.it/tgr/trento/articoli/2022/08/tnt-Elezioni-del-25-settembre-come-si-vota-ad6808ce-7add-4c05-851e-0d852650ddc6.html) ti riporto: 

> In Trentino i senatori da eleggere sono tre, tutti in collegi uninominali. In Trentino Alto Adige (e in valle d'Aosta) non c'è collegio proporzionale per i Senatori. Il candidato con un voto in più degli altri viene eletto.
> Alla Camera, in Trentino vengono eletti due deputati con sistema maggioritario in altrettanti collegi uninominali.
> Altri tre deputati vengono eletti con il sistema proporzionale, ma in un collegio unico regionale.
> Anche in Alto Adige verranno eletti 3 senatori e 2 deputati. 

E in Valle d'Aosta si vota con il sistema maggioritario uninominale e vince il candidato che prende più voti.

Non so se sono stato d'aiuto.

**Comment by alberto-bottarini** [comment]
Sei stato molto d'aiuto. E soprattutto velocissimo.
Grazie.
