### ISSUE TITLE
Risultati Valle D'Aosta

### ISSUE THREAD

**Issue by alberto-bottarini** [ondata/elezioni-politiche-2022#30]
Ciao, sbaglio o i risultati della VdA non sono disponibili in nessun file?

**Comment by aborruso** [comment]
Ciao @alberto-bottarini noi lo scraping non l'abbiamo fatto. 

È veramente strano che ancora Eligendo non lo abbia [pubblicati](https://elezioni.interno.gov.it/report/20220925). Non ho verificato, ma da quello che scrivi sarà così :(

**Comment by alberto-bottarini** [comment]
Ho tirato giù i dati dal sito della regione. Genero un csv per una PR? Può interessare?

**Comment by aborruso** [comment]
> Ho tirato giù i dati dal sito della regione. Genero un csv per una PR? Può interessare?

Sì, grazie!!
