### ISSUE TITLE
csv uninominali info su coalizione/lista del candidato

### ISSUE THREAD

**Issue by gabrielepinto** [ondata/elezioni-politiche-2022#4]
è possibile aggiungere la lista/coalizione del candidato nei file csv dei candidati all'uninominale ? ho visto che nel json sono riportati ma non li vedo nei csv

**Comment by aborruso** [comment]
Gabriele, domani ci guardo.

Se è come dici, si può fare certamente.

Grazie per la nota

**Comment by aborruso** [comment]
Grazie @gabrielepinto: nei CSV adesso ne trovi due con suffisso "_coalizioni" https://github.com/ondata/elezioni-politiche-2022/tree/main/liste/processing
