### ISSUE TITLE
Aggiungere il sesso ai file csv

### ISSUE THREAD

**Issue by numshub** [ondata/elezioni-politiche-2022#6]
Il sesso è ricavabile dal codice fiscale.

Ho creato uno script bash che aggiunge il campo sesso ai file csv:

CF_FIELD=`head -n 1 -q $1 | gawk -F, '{print NF}'`                                                                                
gawk -F, -v cf_field=$CF_FIELD '{print $cf_field}' $1 | colrm 1 9 | colrm 3 | gawk '(NR==1) {print "sesso";next} $1<32 {print "M"} $1>31 {print "F"}' | paste -d',' $1 -

Basta integrarlo nello script di generazione dei file csv.

**Comment by aborruso** [comment]
Grazie @numshub
