### ISSUE TITLE
codice fiscale

### ISSUE THREAD

**Issue by gabrielepinto** [ondata/elezioni-politiche-2022#7]
perdonami ho visto che ieri c'era il codice fiscale oggi manca, non so se è voluto.
grazie ancora per questo prezioso strumento

**Comment by aborruso** [comment]
Ciao Gabriele, nei dati grezzi è un'informazione presente. Non vorremmo contribuire alla diffusione di informazioni su cui potrebbe sorgere qualche questione di privacy.

Dobbiamo valutare la cosa

https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ITALIA_20220925/CAMERA_ITALIA_20220925_pluri.json
https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ITALIA_20220925/CAMERA_ITALIA_20220925_uni.json
https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ESTERO_20220925/CAMERA_ESTERO_20220925.json
https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ITALIA_20220925/SENATO_ITALIA_20220925_pluri.json
https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ITALIA_20220925/SENATO_ITALIA_20220925_uni.json
https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ESTERO_20220925/SENATO_ESTERO_20220925.json

**Comment by aborruso** [comment]
Se fai qualcosa con questi dati, segnalacela, che fa piacere
