### ISSUE TITLE
CSV riporta anno e non data nascita

### ISSUE THREAD

**Issue by mfortini** [ondata/elezioni-politiche-2022#8]
Non so se sia voluto, ma dt_nasc nel CSV riporta solo l'anno e non la data di nascita

**Comment by aborruso** [comment]
Ciao @mfortini ci arrivano alert sulla privacy, e la cosa sarebbe da verificare. E non riusciamo a farlo subito.

Qui i dati dalla fonte:

- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ITALIA_20220925/CAMERA_ITALIA_20220925_pluri.json
- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ITALIA_20220925/CAMERA_ITALIA_20220925_uni.json
- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/CAMERA_ESTERO_20220925/CAMERA_ESTERO_20220925.json
- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ITALIA_20220925/SENATO_ITALIA_20220925_pluri.json
- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ITALIA_20220925/SENATO_ITALIA_20220925_uni.json
- https://dait.interno.gov.it/documenti/trasparenza/POLITICHE_20220925/SENATO_ESTERO_20220925/SENATO_ESTERO_20220925.json

**Comment by aborruso** [comment]
Il sottinteso: sì, è voluto
